// defines the API endpoints used in the application
export const apiEndpoints = {
	auth: {
		signIn: '/auth/sign-in',
		refreshToken: '/auth/refresh-token',
		signUp: '/auth/sign-up',
		verifyEmail: '/auth/verify-email',
		forgotPassword: '/auth/forgot-password',
		verifyResetPasswordOtp: '/auth/verify-reset-password-otp',
		resetPassword: '/auth/reset-password',
		signOut: '/auth/sign-out',
	},
	products: {
		getAll: '/products',
		getById: (id: number) => `/products/${id}`,
		create: '/products',
		update: (id: number) => `/products/${id}`, // TODO: update partial
		delete: (id: number) => `/products/${id}`,
	},
	categories: {
		getAll: '/categories',
		create: '/categories',
		update: (id: number) => `/categories/${id}`,
		delete: (id: number) => `/categories/${id}`,
	},
	promotions: {
		getAll: '/promotions',
		getById: (id: number) => `/promotions/${id}`,
		create: '/promotions',
		update: (id: number) => `/promotions/${id}`,
		delete: (id: number) => `/promotions/${id}`,
	},
	cart: {
		get: '/cart',
		addItem: (id: number) => `/cart/${id}`,
		updateQuantity: (id: number) => `/cart/${id}`,
		deleteItem: (id: number) => `/cart/${id}`,
		clear: '/cart',
	},
	users: {
		getProfile: '/users/me',
		updateProfile: '/users/me',
		changePassword: '/users/change-password',
		assignAccount: '/users/assign-account',
		// Admin operations
		getAll: '/users',
		getLocked: '/users/locked',
		restore: (id: number) => `/users/${id}/restore`,
		lock: (id: number) => `/users/${id}`,
		shippingAddresses: {
			getAll: '/users/shipping-addresses',
			getById: (id: number) => `/users/shipping-addresses/${id}`,
			create: '/users/shipping-addresses',
			update: (id: number) => `/users/shipping-addresses/${id}`,
			delete: (id: number) => `/users/shipping-addresses/${id}`,
		},
	},
	orders: {
		getAll: '/orders',
		getById: (id: number) => `/orders/${id}`,
		create: '/orders',
		updateStatus: (id: number) => `/orders/${id}`,
		cancel: (id: number) => `/orders/${id}/cancel`,
		delete: (id: number) => `/orders/${id}`,
	},
	reviews: {
		getAll: '/reviews',
		getById: (id: number) => `/reviews/${id}`,
		getByProduct: (productId: number) => `/reviews/product/${productId}`,
		getMy: '/reviews/my',
		create: (productId: number) => `/reviews/${productId}`,
		update: (id: number) => `/reviews/${id}`,
		delete: (id: number) => `/reviews/${id}`,
	},
	delivery: {
		getAll: '/deliveries',
		getByEmployee: '/deliveries/employee',
		create: (orderId: number, employeeId: number) =>
			`/deliveries/${orderId}/${employeeId}`,
		updateStatus: (id: number) => `/deliveries/${id}/status`,
		updatePartial: (id: number) => `/deliveries/${id}`,
	},
	batches: {
		getAll: '/batches',
		getById: (id: number) => `/batches/${id}`,
		create: '/batches',
		update: (id: number) => `/batches/${id}`,
		dispose: (id: number) => `/batches/${id}/dispose`,
		delete: (id: number) => `/batches/${id}`,
	},
	prescriptions: {
		getMy: '/prescriptions/my',
		getMyById: (id: number) => `/prescriptions/my/${id}`,
		getApproved: '/prescriptions/approved',
		getAllForPharmacist: '/prescriptions',
		create: '/prescriptions',
		approve: (id: number) => `/prescriptions/${id}/approve`,
		reject: (id: number) => `/prescriptions/${id}/reject`,
	},
	notifications: {
		getAll: '/notifications',
		markAsRead: (id: number) => `/notifications/${id}/read`,
		markAllAsRead: '/notifications/read-all',
	},
};
